// <auto-generated />
using HospitalAllocation.Model;
using HospitalAllocation.Providers.CSVFile.Interface;
using HospitalAllocation.Providers.Image.Interface;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using Microsoft.EntityFrameworkCore.ValueGeneration;
using System;

namespace HospitalAllocation.Migrations
{
    [DbContext(typeof(AllocationContext))]
    [Migration("20180731123745_AddCsvAndHandover")]
    partial class AddCsvAndHandover
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.0-rtm-26452");

            modelBuilder.Entity("HospitalAllocation.Model.CSVFileStorage", b =>
                {
                    b.Property<int>("CSVFileID")
                        .ValueGeneratedOnAdd();

                    b.Property<byte[]>("CSVFileData")
                        .IsRequired();

                    b.Property<int>("CSVFileFormat");

                    b.Property<DateTime>("CSVTimeStamp");

                    b.HasKey("CSVFileID");

                    b.HasIndex("CSVTimeStamp");

                    b.ToTable("CSVFileStorages");
                });

            modelBuilder.Entity("HospitalAllocation.Model.Designation", b =>
                {
                    b.Property<int>("DesignationId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("DesignationId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Designations");
                });

            modelBuilder.Entity("HospitalAllocation.Model.Handover", b =>
                {
                    b.Property<int>("HandoverID")
                        .ValueGeneratedOnAdd();

                    b.Property<DateTime>("AdmissionDate");

                    b.Property<string>("AdmissionUnit")
                        .IsRequired();

                    b.Property<string>("Alerts")
                        .IsRequired();

                    b.Property<string>("BedNumber")
                        .IsRequired();

                    b.Property<string>("Isolation");

                    b.Property<string>("NurseName");

                    b.Property<string>("PastMedicalHistory");

                    b.Property<string>("PatientId")
                        .IsRequired();

                    b.Property<string>("PatientName")
                        .IsRequired();

                    b.Property<string>("PresentingComplaint");

                    b.Property<string>("SignificantEvents");

                    b.Property<string>("StudentName");

                    b.Property<bool>("SwabSent");

                    b.Property<DateTime>("SwabSentDate");

                    b.HasKey("HandoverID");

                    b.ToTable("Handovers");
                });

            modelBuilder.Entity("HospitalAllocation.Model.HandoverIssue", b =>
                {
                    b.Property<int>("HandoverIssueId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CurrentIssue");

                    b.Property<string>("FollowUp");

                    b.Property<int?>("HandoverID")
                        .IsRequired();

                    b.Property<int>("IssueNumber");

                    b.Property<string>("Management");

                    b.HasKey("HandoverIssueId");

                    b.HasIndex("HandoverID");

                    b.ToTable("HandoverIssues");
                });

            modelBuilder.Entity("HospitalAllocation.Model.Note", b =>
                {
                    b.Property<int>("NoteId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Contents")
                        .IsRequired();

                    b.Property<long>("CreationTime");

                    b.Property<long>("LastModificationTime");

                    b.Property<int>("StaffMemberId");

                    b.HasKey("NoteId");

                    b.HasIndex("StaffMemberId");

                    b.ToTable("Notes");
                });

            modelBuilder.Entity("HospitalAllocation.Model.Photo", b =>
                {
                    b.Property<int>("PhotoId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("Format");

                    b.Property<byte[]>("Image")
                        .IsRequired();

                    b.HasKey("PhotoId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("HospitalAllocation.Model.Position", b =>
                {
                    b.Property<int>("PositionId")
                        .ValueGeneratedOnAdd();

                    b.Property<int?>("AllocationId")
                        .IsRequired();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int>("ShiftType");

                    b.Property<int?>("Type")
                        .IsRequired();

                    b.HasKey("PositionId");

                    b.HasIndex("AllocationId");

                    b.ToTable("Position");

                    b.HasDiscriminator<string>("Discriminator").HasValue("Position");
                });

            modelBuilder.Entity("HospitalAllocation.Model.PositionTypeEntry", b =>
                {
                    b.Property<int>("PositionTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Type");

                    b.HasKey("PositionTypeId");

                    b.HasAlternateKey("Type");

                    b.ToTable("PositionTypes");
                });

            modelBuilder.Entity("HospitalAllocation.Model.Skill", b =>
                {
                    b.Property<int>("SkillId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<string>("Name")
                        .IsRequired();

                    b.HasKey("SkillId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("HospitalAllocation.Model.StaffMember", b =>
                {
                    b.Property<int>("StaffMemberId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Alias");

                    b.Property<int?>("DesignationId");

                    b.Property<string>("FirstName")
                        .IsRequired();

                    b.Property<long?>("LastDouble");

                    b.Property<string>("LastName");

                    b.Property<int?>("PhotoId");

                    b.Property<int?>("RosterOnId");

                    b.HasKey("StaffMemberId");

                    b.HasIndex("DesignationId");

                    b.HasIndex("PhotoId");

                    b.ToTable("StaffMembers");
                });

            modelBuilder.Entity("HospitalAllocation.Model.StaffPosition", b =>
                {
                    b.Property<int>("StaffPositionId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<int?>("PositionId")
                        .IsRequired();

                    b.HasKey("StaffPositionId");

                    b.HasIndex("PositionId")
                        .IsUnique();

                    b.ToTable("StaffPosition");

                    b.HasDiscriminator<string>("Discriminator").HasValue("StaffPosition");
                });

            modelBuilder.Entity("HospitalAllocation.Model.StaffSkill", b =>
                {
                    b.Property<int>("StaffSkillId")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("SkillId");

                    b.Property<int>("StaffMemberId");

                    b.HasKey("StaffSkillId");

                    b.HasIndex("SkillId");

                    b.HasIndex("StaffMemberId");

                    b.ToTable("StaffSkill");
                });

            modelBuilder.Entity("HospitalAllocation.Model.TeamAllocation", b =>
                {
                    b.Property<int>("TeamAllocationId")
                        .ValueGeneratedOnAdd();

                    b.Property<long>("Time");

                    b.Property<int?>("Type")
                        .IsRequired();

                    b.HasKey("TeamAllocationId");

                    b.HasAlternateKey("Type", "Time");

                    b.ToTable("TeamAllocations");
                });

            modelBuilder.Entity("HospitalAllocation.Model.TeamTypeEntry", b =>
                {
                    b.Property<int>("TeamTypeId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name")
                        .IsRequired();

                    b.Property<int>("Type");

                    b.HasKey("TeamTypeId");

                    b.HasAlternateKey("Type");

                    b.ToTable("TeamTypes");
                });

            modelBuilder.Entity("HospitalAllocation.Model.BedPosition", b =>
                {
                    b.HasBaseType("HospitalAllocation.Model.Position");

                    b.Property<int>("Position");

                    b.ToTable("BedPosition");

                    b.HasDiscriminator().HasValue("BedPosition");
                });

            modelBuilder.Entity("HospitalAllocation.Model.KnownStaffPosition", b =>
                {
                    b.HasBaseType("HospitalAllocation.Model.StaffPosition");

                    b.Property<int?>("StaffMemberId")
                        .IsRequired();

                    b.HasIndex("StaffMemberId");

                    b.ToTable("KnownStaffPosition");

                    b.HasDiscriminator().HasValue("KnownStaffPosition");
                });

            modelBuilder.Entity("HospitalAllocation.Model.UnknownStaffPosition", b =>
                {
                    b.HasBaseType("HospitalAllocation.Model.StaffPosition");

                    b.Property<string>("StaffName");

                    b.ToTable("UnknownStaffPosition");

                    b.HasDiscriminator().HasValue("UnknownStaffPosition");
                });

            modelBuilder.Entity("HospitalAllocation.Model.HandoverIssue", b =>
                {
                    b.HasOne("HospitalAllocation.Model.Handover", "Handover")
                        .WithMany("HandoverIssues")
                        .HasForeignKey("HandoverID")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalAllocation.Model.Note", b =>
                {
                    b.HasOne("HospitalAllocation.Model.StaffMember", "StaffMember")
                        .WithMany("Notes")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalAllocation.Model.Position", b =>
                {
                    b.HasOne("HospitalAllocation.Model.TeamAllocation", "Allocation")
                        .WithMany("Positions")
                        .HasForeignKey("AllocationId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalAllocation.Model.StaffMember", b =>
                {
                    b.HasOne("HospitalAllocation.Model.Designation", "Designation")
                        .WithMany("StaffMembers")
                        .HasForeignKey("DesignationId");

                    b.HasOne("HospitalAllocation.Model.Photo", "Photo")
                        .WithMany()
                        .HasForeignKey("PhotoId");
                });

            modelBuilder.Entity("HospitalAllocation.Model.StaffPosition", b =>
                {
                    b.HasOne("HospitalAllocation.Model.Position", "Position")
                        .WithOne("StaffPosition")
                        .HasForeignKey("HospitalAllocation.Model.StaffPosition", "PositionId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalAllocation.Model.StaffSkill", b =>
                {
                    b.HasOne("HospitalAllocation.Model.Skill", "Skill")
                        .WithMany("StaffSkills")
                        .HasForeignKey("SkillId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HospitalAllocation.Model.StaffMember", "StaffMember")
                        .WithMany("StaffSkills")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HospitalAllocation.Model.KnownStaffPosition", b =>
                {
                    b.HasOne("HospitalAllocation.Model.StaffMember", "StaffMember")
                        .WithMany("Positions")
                        .HasForeignKey("StaffMemberId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
